server:
  port: 8080

spring:
  application:
    name: inventory-receipt
  cloud:
    config:
      profile: dev
  config:
    import: "optional:configserver:http://localhost:8088"
  datasource:
    url: jdbc:mysql://103.162.20.252:24806/${database.name}?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=${time.zone}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${database.username}
    password: ${database.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en